const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8');
const helpers=html.slice(html.indexOf('function jenisRekodGraf'),html.indexOf('function paparGraf'));
const DB={records:[{'ATLET ID':'A',TARIKH:'2026-01-01',MASA:'09:00',NILAI:14.5},{'ATLET ID':'A',TARIKH:'2026-02-01',MASA:'09:00',NILAI:13.4,CATATAN:'[EVENT: MSSK] Akhir'},{'ATLET ID':'OTHER',TARIKH:'2026-01-01',NILAI:9.5}]};
const ctx={acaraInfo:()=>({JENIS:'MASA'}),penyertaan:()=>[{'ATLET ID':'A','REKOD PERIBADI':'1:15.45',KATEGORI:'L15'}],rekodAcara:()=>DB.records,rekodMilik:(r,id)=>r['ATLET ID'].split(',').map(s=>s.trim()).includes(id),masaKunci:s=>s||'',huraiMasa:s=>s.includes(':')?Number(s.split(':')[0])*60+Number(s.split(':')[1]):Number(s),kejohananKatSemua:()=>[{NILAI:12.55}]};
vm.createContext(ctx);vm.runInContext(helpers,ctx);
const d=ctx.dataGraf('100 M','A');
assert.equal(d.rekod.length,2,'Only this athlete records');
assert.equal(d.pb,75.45,'PB minute format converted to seconds');
assert.equal(d.terbaik,13.4,'Lower time is better');
assert.equal(ctx.jenisRekodGraf(d.rekod[1]),'EVENT','Meet result separate from training');
assert.equal(ctx.dataGraf('100 M','A','2026-02-01').rekod.length,1,'Date range applies');
ctx.acaraInfo=()=>({JENIS:'JARAK'});
assert.equal(ctx.dataGraf('LOMPAT JAUH','A').terbaik,14.5,'Higher distance is better');
console.log('6 performance graph rules passed');
