const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
const source=html.slice(html.indexOf('function formRekodProfil('),html.indexOf('function vProfil('));
let permitted=true,team=false,joined=true,calls=[];
const checkbox=[{value:'A',checked:false},{value:'B',checked:true}];
const ctx={bolehRekod:()=>permitted,penyertaan:()=>joined?[{'ATLET ID':'A'}]:[],isBerpasukan:()=>team,formRekod:(n,id)=>calls.push(['individual',n,id]),formRekodRelay:n=>calls.push(['team',n]),toast:()=>calls.push(['denied']),document:{querySelectorAll:()=>checkbox}};
vm.createContext(ctx);vm.runInContext(source,ctx);
ctx.formRekodProfil('LOMPAT JAUH','A');
assert.deepEqual(calls,[['individual','LOMPAT JAUH','A']],'Record uses profile athlete and selected event');
calls=[];permitted=false;ctx.formRekodProfil('100 M','A');
assert.deepEqual(calls,[['denied']],'Existing record permissions are preserved');
calls=[];permitted=true;joined=false;ctx.formRekodProfil('100 M','A');
assert.deepEqual(calls,[['denied']],'Cannot record an event athlete has not joined');
calls=[];joined=true;team=true;ctx.formRekodProfil('4 X 400M','A');
assert.deepEqual(calls,[['team','4 X 400M']]);
assert.deepEqual(checkbox.map(x=>x.checked),[true,false],'Team form preselects only profile athlete');
console.log('4 profile record rules passed');